### PR TITLE
Update AU, NZ, KZ and BR

### PR DESCRIPTION
**Pull request by gradoj**
Moved Kazakhstan from EU433 to IN865
Moved Australia and New Zealand from AS923-1 to AS923-1C 
Moved Brazil from AU915 to AU915-SB1
removed British Virgin Islands from unknown as it was already covered.

### CODE REVIEW

**Comment by madninja** [comment]
Can we get #21 merged so that you no longer have to check in h3idx binaries but only update the geojson reference for the submodule? (which this PR is missing)

**Comment by gradoj** [comment]
Would it be easiest to just close this for now?

**Comment by madninja** [comment]
> Would it be easiest to just close this for now?

Or fix it/open a new one to just update the hplans submodule git ref

**Comment by JayKickliter** [comment]
> Can we get #21 merged so that you no longer have to check in h3idx binaries but only update the geojson reference for the submodule? (which this PR is missing)

The only thing blocking 21 is draft status.

**Comment by madninja** [comment]
> > Can we get #21 merged so that you no longer have to check in h3idx binaries but only update the geojson reference for the submodule? (which this PR is missing)
> 
> The only thing blocking 21 is draft status.

Good point! Fixed

**Pull request closed without merging**
